---
- name: Getting public ip address
  ipify_facts:
  register: ip_info

- name: Setting ip fact
  set_fact:
    public_ip: "{{ ip_info.ansible_facts.ipify_public_ip }}"

- name: Creating teleport config directory
  become: yes
  file:
    path: "{{ teleport_config_dir }}"
    owner: "ubuntu"
    group: "ubuntu"
    state: directory

- name: Creating teleport config
  become: yes
  template:
    src: "teleport.yml.j2"
    dest: "{{ teleport_config_path }}"
    force: yes
    owner: "ubuntu"
    group: "ubuntu"
    mode: "u=r"
