---
- name: Create user
  user:
    name: ubuntu

- name: Create teleport variable directory
  become: yes
  file:
    path: "{{ teleport_data_dir }}"
    owner: "ubuntu"
    group: "ubuntu"
    state: directory

- name: Creating teleport config directory
  become: yes
  file:
    path: "{{ teleport_config_dir }}"
    owner: "ubuntu"
    group: "ubuntu"
    state: directory

- name: Create teleport ssl directory
  become: yes
  file:
    path: "{{ teleport_ssl_dir }}"
    owner: "ubuntu"
    group: "ubuntu"
    state: directory

- name: Copy license file
  when: teleport_enterprise_mode
  copy:
    src: "{{ teleport_auth_service_license_src }}"
    dest: "{{ teleport_auth_service_license_file }}"
    owner: "ubuntu"
    group: "ubuntu"
    mode: '0400'

- name: Generating join tokens
  when: inventory_hostname == groups['teleport_auth'][0] and not teleport_auth_token is defined
  become: yes
  command: tctl nodes add --ttl=10m --roles="auth,proxy,node"
  register: tctl_result

# Uses a Perl compatible regex (-P) for positive lookbehind
- name: Grabbing token
  when: not tctl_result is skipped
  shell: echo "{{ tctl_result.stdout }}" | grep -oP "(?<=--token=)[A-Za-z0-9]*"
  register: token

- name: Saving token
  when: not tctl_result is skipped
  set_fact:
    "join_token": "{{ token.stdout }}"

- name: Saving CA pin output
  when: inventory_hostname == groups['teleport_auth'][0] and teleport_use_ca_pin
  become: true
  command: tctl status
  register: ca_pin_output

- name: Saving CA pin
  when: not ca_pin_output is skipped
  set_fact:
    "ca_pin": "{{ ca_pin_output.stdout_lines[3].split(' ')[2] }}"

- name: Creating teleport config
  become: yes
  template:
    src: "teleport.yml.j2"
    dest: "{{ teleport_config_path }}"
    force: yes
    owner: "ubuntu"
    group: "ubuntu"
    mode: "u=r"
  notify: reload teleport

- name: Creating teleport unit file
  become: true
  template:
    src: "teleport.service.j2"
    dest: "{{ teleport_service_path }}"
    force: true
    owner: "ubuntu"
    group: "ubuntu"
    mode: "u=rw,g=rw,o=r"
  notify: restart teleport
