---
- name: Creating teleport config directory
  become: yes
  file:
    path: "{{ teleport_config_dir }}"
    owner: "ubuntu"
    group: "ubuntu"
    state: directory

- name: Creating teleport config
  become: yes
  template:
    src: "teleport.yml.j2"
    dest: "{{ teleport_config_path }}"
    force: yes
    owner: "ubuntu"
    group: "ubuntu"
    mode: "u=r"
