---
- name: Create user
  user:
    name: ubuntu

- name: Create teleport variable directory
  become: yes
  file:
    path: "{{ teleport_data_dir }}"
    owner: "ubuntu"
    group: "ubuntu"
    state: directory

- name: Creating teleport config directory
  become: yes
  file:
    path: "{{ teleport_config_dir }}"
    owner: "ubuntu"
    group: "ubuntu"
    state: directory

- name: Create teleport ssl directory
  become: yes
  file:
    path: "{{ teleport_ssl_dir }}"
    owner: "ubuntu"
    group: "ubuntu"
    state: directory

# removes backslash to prevent a escape character from being generated
# which can confuse ansible stdout
- name: Generate join token
  shell: 'openssl rand -base64 64 | tr -d \'
  register: join_token

- name: Set join token as fact
  set_fact:
    join_token: "{{ join_token.stdout }}"

- name: Creating teleport config
  become: yes
  template:
    src: "teleport.yml.j2"
    dest: "{{ teleport_config_path }}"
    force: yes
    owner: "ubuntu"
    group: "ubuntu"
    mode: "u=r"

- name: Creating teleport unit file
  become: true
  template:
    src: "teleport.service.j2"
    dest: "{{ teleport_service_path }}"
    force: true
    owner: "ubuntu"
    group: "ubuntu"
    mode: "u=rw,g=rw,o=r"
