---
# TODO: delegating to localhost to reduce the number of downloads from
# remote server
- name: Download teleport
  when: not ansible_check_mode
  unarchive:
    remote_src: yes
    src: "{{ teleport_url }}"
    dest: "/tmp"
  register: _download_teleport
  until: _download_teleport is success
  retries: 10
  delay: 2
