---
- name: Download teleport archive to localhost
  get_url:
    url: "https://get.gravitational.com/teleport-{{ teleport_version }}-{{ teleport_node_arch }}-bin.tar.gz"
    dest: "/tmp/"
  register: _download_teleport
  until: _download_teleport is success
  retries: 10
  delay: 2
  delegate_to: localhost
