---
- name: Unpack teleport
  unarchive:
    src: "/tmp/teleport-{{ teleport_version }}-{{ teleport_node_arch }}-bin.tar.gz"
    dest: "/tmp"
    creates: "/tmp/teleport/"

- name: Install teleport
  become: yes
  command: "/tmp/teleport/install"

- name: Remove teleport download
  become: yes
  file:
    path: "/tmp/teleport"
    state: absent
