---
- name: Create package dir
  file:
    path: "/tmp/teleport-{{ teleport_version }}-{{ teleport_node_arch }}/"
    state: directory

- name: Unpack teleport
  unarchive:
    src: "/tmp/teleport-{{ teleport_version }}-{{ teleport_node_arch }}-bin.tar.gz"
    dest: "/tmp/teleport-{{ teleport_version }}-{{ teleport_node_arch }}"

- name: Install teleport
  when: >
    (not _teleport_installed.stat.exists) or
    ( not _teleport_version_output.stdout |
      regex_search('teleport ' + teleport_version, ignorecase=True) )
  become: yes
  command: "/tmp/teleport-{{ teleport_version }}-{{ teleport_node_arch }}/teleport/install"

- name: Remove teleport package
  become: yes
  file:
    path: "/tmp/teleport-{{ teleport_version }}-{{ teleport_node_arch }}/"
    state: absent
