---
- name: Unpack teleport
  unarchive:
    src: "/tmp/teleport-ent-{{ teleport_version }}-{{ teleport_node_arch }}-bin.tar.gz"
    dest: "/tmp"

- name: Install teleport
  become: yes
  command: "/tmp/teleport-ent/install"

- name: Remove teleport download
  become: yes
  file:
    path: "/tmp/teleport"
    state: absent
