---
- import_tasks: preflight.yml
  tags:
    - always

- import_tasks: download.yml
  when: >
    (not _teleport_installed.stat.exists) or
    ( not _teleport_version_output.stdout | regex_search('teleport .*' + teleport_version, ignorecase=True) )
  tags:
    - teleport_install
    - teleport_upgrade

- import_tasks: install.yml
  when: >
    (not _teleport_installed.stat.exists) or
    ( not _teleport_version_output.stdout | regex_search('teleport .*' + teleport_version, ignorecase=True) )
  tags:
    - teleport_install
    - teleport_upgrade

- import_tasks: configure.yml
  tags:
    - teleport_install
    - teleport_update
