---
- import_tasks: preflight.yml
  tags:
    - always

- import_tasks: download.yml
  when: >
    (not _teleport_installed.stat.exists) or
    ( not _teleport_version_output.stdout | regex_search(teleport_version, ignorecase=True) )

- import_tasks: install.yml
  when: >
    (not teleport_enterprise_mode) and
    ((not _teleport_installed.stat.exists) or
    ( not _teleport_version_output.stdout |
      regex_search('teleport ' + teleport_version, ignorecase=True) ))

- import_tasks: install-ent.yml
  when: >
    (teleport_enterprise_mode) and
    ((not _teleport_installed.stat.exists) or
    ( not _teleport_version_output.stdout |
      regex_search('teleport enterprise ' + teleport_version, ignorecase=True) ))

- import_tasks: configure.yml
