---
# cloudalchemy/ansible-node-exporter reference
- name: Assert usage of systemd as an init system
  assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This role only works with systemd"

- name: Check if teleport is installed
  stat:
    path: "/usr/local/bin/teleport"
  register: _teleport_installed

- name: Gather teleport version
  when: _teleport_installed.stat.exists
  command: "/usr/local/bin/teleport version"
  register: _teleport_version_output

- name: Getting public ip address
  ipify_facts:
  register: ip_info

- name: Setting ip fact
  set_fact:
    public_ip: "{{ ip_info.ansible_facts.ipify_public_ip }}"
