---
# Use start and reload steps to allow new teleport clients to start
# and existing clients to perform graceful restarts
# It is important that 'restart' is async as restarting of teleport will
# terminate existing connections (which are what ansible is using)
- name: restart teleport
  listen: "restart teleport"
  become: true
  async: 60
  poll: 0
  systemd:
    name: "teleport.service"
    daemon-reload: yes
    enabled: yes
    state: restarted
  register: teleport_restarted

- name: reload teleport
  become: true
  when: not teleport_restarted
  systemd:
    name: "teleport.service"
    state: reloaded
    enabled: yes

- name: wait for teleport restart
  listen: "restart teleport"
  wait_for_connection:
    timeout: 60
    delay: 2
