---
# Use start and reload steps to allow new teleport clients to start
# and existing clients to perform graceful restarts
- name: restart teleport
  become: true
  service:
    name: teleport
    enabled: yes
    state: restarted

- name: reload teleport
  become: true
  service:
    name: teleport
    state: reloaded
