---
# Use start and reload steps to allow new teleport clients to start
# and existing clients to perform graceful restarts
- name: restart teleport
  become: true
  systemd:
    name: "teleport.service"
    daemon-reload: yes
    enabled: yes
    state: restarted

- name: reload teleport
  become: true
  systemd:
    name: "teleport.service"
    state: reloaded
    enabled: yes
