---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: node-1
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu1804}-ansible:testing
    groups:
      - node
  - name: proxy-1
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu1804}-ansible:testing
    groups:
      - proxy
  - name: auth-1
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu1804}-ansible:testing
    groups:
      - auth
provisioner:
  name: ansible
  log: True
  options:
    v: True
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  options:
    v: 1
  lint:
    name: flake8
